
export enum AppMode {
  TRACKLY = 'trackly',
  POS = 'pos',
  KDS = 'kds'
}

export enum ProjectContext {
  THE_YARD = 'the-yard',
  SUNDAY_THEORY = 'sunday-theory'
}

export enum UserRole {
  OWNER = 'owner',
  MANAGER = 'manager',
  SERVER = 'server',
  KITCHEN = 'kitchen',
  BARTENDER = 'bartender'
}

export enum PresenceStatus {
  AT_DESK = 'at-desk',
  LUNCH = 'lunch',
  MEETING = 'meeting',
  OUT_OF_OFFICE = 'out-of-office',
  LEAVE = 'leave',
  ON_SHIFT = 'on-shift',
  FOCUS = 'focus'
}

export enum Responsibility {
  DASHBOARD = 'dashboard',
  TASKS = 'tasks',
  CALENDAR = 'calendar',
  MEETINGS = 'meetings',
  SUPPLY_CHAIN = 'supply-chain',
  TICKETING = 'ticketing',
  EXECUTION = 'execution',
  EVENTS = 'events',
  INSIGHTS = 'insights',
  REPORTS = 'reports',
  STAFF = 'staff',
  SHIFT_PLANNER = 'shift-planner',
  WELLNESS = 'wellness',
  PAYROLL = 'payroll',
  POS = 'pos-terminal',
  KDS = 'kds',
  BILLS = 'bills',
  MENU_MANAGER = 'menu-manager'
}

export interface UserProfile {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  avatar: string;
  pin: string;
  defaultContext: ProjectContext;
  responsibilities: Responsibility[];
  baseHourlyRate: number;
  overtimeMultiplier: number;
  overtimeThreshold: number;
  birthday?: string; // Format: MM-DD
}

export interface TeamMember extends UserProfile {
  status: PresenceStatus;
  context: ProjectContext;
  workStartTime?: string;
  currentTask?: string;
  statusExpiresAt?: string;
}

export interface PayrollRecord {
  id: string;
  memberId: string;
  periodStart: string;
  periodEnd: string;
  standardHours: number;
  overtimeHours: number;
  grossPay: number;
  deductions: number;
  netPay: number;
  status: 'pending' | 'processed' | 'paid';
}

export enum ShiftType {
  PREP = 'prep',
  PRE_DUTY = 'pre-duty',
  LUNCH = 'lunch',
  DINNER = 'dinner',
  EVENT = 'event',
  CLOSING = 'closing'
}

export enum DeliveryCategory {
  KITCHEN = 'kitchen',
  BAR = 'bar',
  OFFICE = 'office'
}

export enum ChecklistCategory {
  PRE_EVENT = 'pre-event',
  EVENT_DAY_BEFORE = 'event-day-before',
  DURING_EVENT = 'during-event',
  POST_EVENT = 'post-event'
}

export interface ChecklistItem {
  id: string;
  task: string;
  category: ChecklistCategory;
  department: DeliveryCategory | 'host' | 'general';
  status: 'todo' | 'in-progress' | 'done';
  timeAnchor?: string;
  autoGenerated: boolean;
}

export interface SupplierItem {
  id: string;
  name: string;
  price: number;
  unit: string;
}

export interface Supplier {
  id: string;
  name: string;
  category: DeliveryCategory;
  contact: string;
  reliability: number;
  avgLeadTime: string;
  catalog: SupplierItem[];
}

export interface OrderLineItem {
  name: string;
  quantity: number;
  unit: string;
  currentStock: number;
  suggestedQty: number;
  priceAtOrder?: number;
}

export interface ProcurementOrder {
  id: string;
  supplierId: string;
  category: DeliveryCategory;
  items: OrderLineItem[];
  status: 'suggested' | 'ordered' | 'confirmed' | 'delivered' | 'delayed';
  dispatchDate?: string;
  expectedDate: string;
  expectedTime?: string;
  leadTimeDays?: number;
  totalCost: number;
  deliveryFee: number;
  context: ProjectContext;
  createdBy: string;
  suggestionReason?: string;
}

export interface TicketType {
  id: string;
  name: string;
  price: number;
  sold: number;
  capacity: number;
  type: 'early-bird' | 'general' | 'vip' | 'complimentary';
}

export interface EventTicketing {
  eventId: string;
  tickets: TicketType[];
  scannedCount: number;
  historicalShowRate: number;
  walkInEstimate: number;
}

export enum TaskStatus {
  TODO = 'todo',
  IN_PROGRESS = 'in-progress',
  REVIEW = 'review',
  DONE = 'done'
}

export type TaskPriority = 'low' | 'medium' | 'high' | 'critical';
export type TaskCategory = 'ops' | 'events' | 'pos' | 'kitchen' | 'bar' | 'admin' | 'maintenance' | 'marketing' | 'other';
export type RecurrenceType = 'none' | 'weekly' | 'monthly' | 'custom';

export interface Task {
  id: string;
  title: string;
  description: string;
  status: TaskStatus;
  assignees: string[];
  reviewerId?: string; 
  dueDate: string;
  priority: TaskPriority;
  isRecurring: boolean;
  recurrenceType: RecurrenceType;
  context: ProjectContext;
  progress: number;
  category: TaskCategory;
  linkedEventId?: string;
  linkedMenuItemId?: string;
  dependencies?: string[];
  estimatedMinutes?: number;
  attachmentUrl?: string;
  attachmentName?: string;
  projectNotes?: string;
  submissionNotes?: string;
}

export interface MenuItem {
  id: string;
  name: string;
  price: number;
  category: string;
  stock: number;
  context: ProjectContext;
  isHubbly?: boolean;
  variants?: string[];
  availableToStaff?: boolean;
}

export interface OrderItem extends MenuItem {
  quantity: number;
  selectedVariant?: string;
  modifiers?: string[];
  isStaffMeal?: boolean;
}

export interface Order {
  id: string;
  tableNumber: string;
  items: OrderItem[];
  status: 'pending' | 'preparing' | 'ready' | 'delivered' | 'paid';
  total: number;
  serverName: string;
  timestamp: string;
  context: ProjectContext;
  isStaffOrder?: boolean;
}

export interface Performer {
  id: string;
  name: string;
  role: 'band' | 'solo' | 'dj' | 'spoken-word';
  arrivalTime: string;
  performanceTime: string;
  rider: string[];
  contact: string;
  tableAssignment?: string;
}

export interface Event {
  id: string;
  name: string;
  date: string;
  startTime: string;
  endTime: string;
  performers: Performer[];
  expectedAttendance: number;
  type: string;
  ticketing?: EventTicketing;
  checklists: ChecklistItem[];
  acknowledgedBy: string[];
  context: ProjectContext;
  location: string;
}

export interface Meeting {
  id: string;
  title: string;
  date: string;
  startTime: string;
  endTime: string;
  attendees: string[];
  context: ProjectContext;
  notes?: string;
  type: 'meeting' | 'break' | 'wellness';
  isRecurring?: boolean;
  recurrenceType?: RecurrenceType;
  parentId?: string;
}

export interface Feedback {
  id: string;
  source: 'staff' | 'customer' | 'wifi';
  category: 'food' | 'service' | 'pricing' | 'music' | 'seating';
  severity: 'low' | 'medium' | 'high';
  comment: string;
  resolved: boolean;
  timestamp: string;
}

export interface Email {
  id: string;
  sender: string;
  subject: string;
  receivedAt: string;
  isResponded: boolean;
  urgency: number;
}

export interface Shift {
  id: string;
  memberId: string;
  startTime: string;
  endTime: string;
  location: string;
  context: ProjectContext;
  type: ShiftType;
  requiresTransport?: boolean;
  transportRegion?: string;
}

export interface StockDelivery {
  id: string;
  item: string;
  supplier: string;
  expectedAt: string;
  category: DeliveryCategory;
  createdBy: string;
  status: 'pending' | 'received' | 'delayed' | 'cancelled';
  context: ProjectContext;
}
