
import React, { useState, useEffect } from 'react';
import { ProjectContext, MenuItem, ChecklistCategory, ChecklistItem, DeliveryCategory, Event } from '../types';
import { Calendar, Clock, Users, Mic2, Utensils, Ticket, FileText, ChevronRight, ChevronLeft, Save, Plus, X, Zap, Crown, Armchair } from 'lucide-react';

interface NewEventFormProps {
  context: ProjectContext;
  menu: MenuItem[];
  initialData?: Event | null;
  onCancel: () => void;
  onSave: (eventData: any) => void;
}

const VENUE_ZONES = [
  "The Yard Main Floor",
  "The Yard Deck",
  "Sunday Theory Zone 1",
  "Sunday Theory Zone 2 (VIP)"
];

const NewEventForm: React.FC<NewEventFormProps> = ({ context, menu, initialData, onCancel, onSave }) => {
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState({
    name: '',
    type: 'Performance',
    date: '',
    startTime: '',
    endTime: '',
    expectedAttendance: 100,
    location: VENUE_ZONES[0],
    performers: [{ id: 'p1', name: '', role: '', arrivalTime: '', performanceTime: '', rider: [''], contact: '', tableAssignment: '' }],
    specials: [] as string[],
    seatingNotes: '',
    isTicketed: false,
    ticketPrice: 0,
    maxCapacity: 200,
    notes: ''
  });

  useEffect(() => {
    if (initialData) {
      setFormData({
        name: initialData.name,
        type: initialData.type,
        date: initialData.date,
        startTime: initialData.startTime,
        endTime: initialData.endTime,
        expectedAttendance: initialData.expectedAttendance,
        location: initialData.location || VENUE_ZONES[0],
        performers: initialData.performers,
        specials: [], 
        seatingNotes: '',
        isTicketed: !!initialData.ticketing,
        ticketPrice: initialData.ticketing?.tickets[0]?.price || 0,
        maxCapacity: initialData.ticketing?.tickets[0]?.capacity || 200,
        notes: ''
      });
    }
  }, [initialData]);

  const nextStep = () => setStep(s => Math.min(s + 1, 5));
  const prevStep = () => setStep(s => Math.max(s - 1, 1));

  const addPerformer = () => {
    setFormData({
      ...formData,
      performers: [...formData.performers, { id: `p${Date.now()}`, name: '', role: '', arrivalTime: '', performanceTime: '', rider: [''], contact: '', tableAssignment: '' }]
    });
  };

  const updatePerformer = (idx: number, field: string, value: any) => {
    const newPerformers = [...formData.performers];
    (newPerformers[idx] as any)[field] = value;
    setFormData({ ...formData, performers: newPerformers });
  };

  const handleSave = () => {
    let checklists = initialData?.checklists || [];
    if (!initialData) {
      checklists = [
        { id: 'c-auto-1', task: `Prepare ${formData.location} for doors`, category: ChecklistCategory.EVENT_DAY_BEFORE, department: 'host', status: 'todo', autoGenerated: true },
        { id: 'c-auto-2', task: `Soundcheck for ${formData.performers[0]?.name || 'Talent'}`, category: ChecklistCategory.EVENT_DAY_BEFORE, department: 'general', status: 'todo', timeAnchor: formData.performers[0]?.arrivalTime, autoGenerated: true },
        { id: 'c-auto-3', task: `Pre-batch Event Specials`, category: ChecklistCategory.PRE_EVENT, department: DeliveryCategory.BAR, status: 'todo', autoGenerated: true },
      ];
      
      // Auto-add VIP seating task if Zone 2 is involved
      if (formData.location.includes("Zone 2") || formData.performers.some(p => p.tableAssignment)) {
        checklists.push({ id: 'c-auto-vip', task: `Sanitize and cordoned Zone 2 VIP tables for performers`, category: ChecklistCategory.PRE_EVENT, department: 'host', status: 'todo', autoGenerated: true });
      }
    }

    onSave({
      ...formData,
      checklists,
      context
    });
  };

  const steps = [
    { id: 1, label: 'Basics', icon: Calendar },
    { id: 2, label: 'Talent', icon: Mic2 },
    { id: 3, label: 'Menu', icon: Utensils },
    { id: 4, label: 'Tickets', icon: Ticket },
    { id: 5, label: 'Review', icon: FileText },
  ];

  return (
    <div className="p-12 max-w-5xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center justify-between mb-12">
        <div>
          <h2 className="text-4xl font-black text-slate-900 tracking-tighter uppercase italic leading-none mb-4">
            {initialData ? 'Modify Architecture' : 'Event Architect'}
          </h2>
          <p className="text-slate-400 font-bold uppercase tracking-[0.2em] text-[10px]">Step {step} of 5 • {steps[step - 1].label}</p>
        </div>
        <button onClick={onCancel} className="p-4 bg-slate-100 text-slate-400 rounded-full hover:bg-slate-200 transition-all"><X size={20} /></button>
      </div>

      <div className="flex gap-4 mb-12">
        {steps.map(s => (
          <div key={s.id} className="flex-1">
            <div className={`h-1.5 rounded-full transition-all duration-500 ${step >= s.id ? 'bg-brand-primary' : 'bg-slate-100'}`} />
            <div className="mt-3 flex items-center gap-2">
               <s.icon size={12} className={step >= s.id ? 'text-brand-primary' : 'text-slate-300'} />
               <span className={`text-[9px] font-black uppercase tracking-widest ${step >= s.id ? 'text-brand-primary' : 'text-slate-300'}`}>{s.label}</span>
            </div>
          </div>
        ))}
      </div>

      <div className="bg-white p-12 rounded-[60px] shadow-2xl shadow-black/5 border border-white/50 min-h-[500px] flex flex-col">
        {step === 1 && (
          <div className="space-y-8 animate-in fade-in duration-300">
             <div className="grid grid-cols-2 gap-8">
               <div className="space-y-2">
                  <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 ml-2">Event Title</label>
                  <input 
                    type="text" 
                    placeholder="e.g. Theory Sundowners #13"
                    className="w-full px-8 py-5 bg-slate-50 rounded-[25px] border-2 border-transparent focus:border-brand-primary outline-none font-bold text-lg"
                    value={formData.name}
                    onChange={e => setFormData({...formData, name: e.target.value})}
                  />
               </div>
               <div className="space-y-2">
                  <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 ml-2">Venue Zone</label>
                  <select 
                    className="w-full px-8 py-5 bg-slate-50 rounded-[25px] border-2 border-transparent focus:border-brand-primary outline-none font-black text-xs uppercase tracking-widest"
                    value={formData.location}
                    onChange={e => setFormData({...formData, location: e.target.value})}
                  >
                    {VENUE_ZONES.map(z => <option key={z}>{z}</option>)}
                  </select>
               </div>
             </div>
             <div className="grid grid-cols-3 gap-8">
                <div className="space-y-2">
                  <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 ml-2">Date</label>
                  <input type="date" className="w-full px-8 py-5 bg-slate-50 rounded-[25px] font-bold" value={formData.date} onChange={e => setFormData({...formData, date: e.target.value})} />
                </div>
                <div className="space-y-2">
                  <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 ml-2">Start Time</label>
                  <input type="time" className="w-full px-8 py-5 bg-slate-50 rounded-[25px] font-bold" value={formData.startTime} onChange={e => setFormData({...formData, startTime: e.target.value})} />
                </div>
                <div className="space-y-2">
                  <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 ml-2">End Time</label>
                  <input type="time" className="w-full px-8 py-5 bg-slate-50 rounded-[25px] font-bold" value={formData.endTime} onChange={e => setFormData({...formData, endTime: e.target.value})} />
                </div>
             </div>
             <div className="space-y-2">
                <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 ml-2">Expected Attendance</label>
                <input type="number" className="w-full px-8 py-5 bg-slate-50 rounded-[25px] font-bold" value={formData.expectedAttendance} onChange={e => setFormData({...formData, expectedAttendance: parseInt(e.target.value)})} />
             </div>
          </div>
        )}

        {step === 2 && (
          <div className="space-y-8 animate-in fade-in duration-300">
             <div className="bg-brand-accent/10 p-6 rounded-[30px] border border-brand-accent/20 flex items-center gap-4">
                <Crown className="text-brand-accent" size={24} />
                <p className="text-xs font-bold text-slate-700 italic">Zone 2 is designated as the primary VIP area for performers and esteemed guests.</p>
             </div>
             {formData.performers.map((p, idx) => (
               <div key={p.id} className="p-8 bg-slate-50 rounded-[40px] border border-slate-100 relative group">
                  <div className="grid grid-cols-2 gap-6">
                    <input 
                      placeholder="Performer Name" 
                      className="bg-white px-6 py-4 rounded-2xl font-bold border border-slate-100"
                      value={p.name}
                      onChange={e => updatePerformer(idx, 'name', e.target.value)}
                    />
                    <div className="relative">
                       <Armchair className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-300" size={18} />
                       <input 
                        placeholder="Reserve VIP Table (e.g. VIP-01)" 
                        className="w-full bg-white pl-12 pr-6 py-4 rounded-2xl font-black text-xs uppercase border border-slate-100 focus:border-brand-accent transition-all"
                        value={p.tableAssignment}
                        onChange={e => updatePerformer(idx, 'tableAssignment', e.target.value)}
                      />
                    </div>
                  </div>
                  <div className="grid grid-cols-3 gap-6 mt-4">
                    <input 
                      placeholder="Role (e.g. Lead DJ)"
                      className="bg-white px-6 py-4 rounded-2xl font-bold border border-slate-100"
                      value={p.role}
                      onChange={e => updatePerformer(idx, 'role', e.target.value)}
                    />
                    <input 
                      type="time" title="Arrival Time"
                      className="bg-white px-6 py-4 rounded-2xl font-bold border border-slate-100"
                      value={p.arrivalTime}
                      onChange={e => updatePerformer(idx, 'arrivalTime', e.target.value)}
                    />
                    <input 
                      type="time" title="Performance Time"
                      className="bg-white px-6 py-4 rounded-2xl font-bold border border-slate-100"
                      value={p.performanceTime}
                      onChange={e => updatePerformer(idx, 'performanceTime', e.target.value)}
                    />
                  </div>
                  <div className="mt-4">
                     <textarea 
                        placeholder="Rider Requirements (comma separated)"
                        className="w-full bg-white px-6 py-4 rounded-2xl font-medium border border-slate-100 resize-none h-20"
                        value={p.rider.join(', ')}
                        onChange={e => updatePerformer(idx, 'rider', e.target.value.split(',').map(s => s.trim()))}
                     />
                  </div>
               </div>
             ))}
             <button onClick={addPerformer} className="flex items-center gap-3 text-[10px] font-black uppercase tracking-widest text-brand-primary hover:gap-4 transition-all">
               <Plus size={16} /> Add Another Talent
             </button>
          </div>
        )}

        {step === 3 && (
          <div className="space-y-8 animate-in fade-in duration-300">
             <div className="bg-brand-primary/5 p-8 rounded-[40px] border border-brand-primary/10 mb-8">
                <p className="text-[10px] font-black text-brand-primary uppercase tracking-widest mb-1 flex items-center gap-2"><Zap size={14} fill="currentColor" /> Supply Chain Integration</p>
                <p className="text-xs font-bold text-slate-600">Selecting specials will automatically update the <b>Procurement Module</b> with suggested orders for these items.</p>
             </div>
             <div className="grid grid-cols-2 gap-4 h-64 overflow-y-auto pr-4 custom-scrollbar">
                {menu.filter(i => i.context === context).map(item => (
                  <button 
                    key={item.id}
                    onClick={() => {
                      const exists = formData.specials.includes(item.id);
                      setFormData({
                        ...formData,
                        specials: exists ? formData.specials.filter(id => id !== item.id) : [...formData.specials, item.id]
                      });
                    }}
                    className={`p-6 rounded-3xl border-2 text-left transition-all ${formData.specials.includes(item.id) ? 'bg-brand-primary text-white border-brand-primary' : 'bg-slate-50 border-transparent text-slate-800 hover:border-slate-200'}`}
                  >
                    <p className="text-sm font-black tracking-tight">{item.name}</p>
                    <p className={`text-[10px] font-bold uppercase mt-1 ${formData.specials.includes(item.id) ? 'text-white/60' : 'text-slate-400'}`}>{item.category}</p>
                  </button>
                ))}
             </div>
          </div>
        )}

        {step === 4 && (
          <div className="space-y-8 animate-in fade-in duration-300">
             <div className="flex items-center gap-6 p-8 bg-slate-50 rounded-[40px]">
                <div className={`w-14 h-8 rounded-full p-1 transition-all flex items-center cursor-pointer ${formData.isTicketed ? 'bg-brand-primary' : 'bg-slate-300'}`} onClick={() => setFormData({...formData, isTicketed: !formData.isTicketed})}>
                   <div className={`w-6 h-6 bg-white rounded-full shadow-lg transition-transform ${formData.isTicketed ? 'translate-x-6' : ''}`} />
                </div>
                <div>
                   <h4 className="font-black text-slate-800 uppercase italic">Ticketed Event</h4>
                   <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Enable sales tracking and capacity locks.</p>
                </div>
             </div>
             {formData.isTicketed && (
               <div className="grid grid-cols-2 gap-8 animate-in zoom-in-95 duration-200">
                 <div className="space-y-2">
                    <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 ml-2">Base Ticket Price (R)</label>
                    <input type="number" className="w-full px-8 py-5 bg-slate-50 rounded-[25px] font-bold" value={formData.ticketPrice} onChange={e => setFormData({...formData, ticketPrice: parseInt(e.target.value)})} />
                 </div>
                 <div className="space-y-2">
                    <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 ml-2">Maximum Venue Capacity</label>
                    <input type="number" className="w-full px-8 py-5 bg-slate-50 rounded-[25px] font-bold" value={formData.maxCapacity} onChange={e => setFormData({...formData, maxCapacity: parseInt(e.target.value)})} />
                 </div>
               </div>
             )}
          </div>
        )}

        {step === 5 && (
          <div className="space-y-8 animate-in fade-in duration-300 flex-1">
             <div className="grid grid-cols-2 gap-12">
                <div className="space-y-6">
                   <div>
                      <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Architecture Summary</p>
                      <h3 className="text-3xl font-black text-slate-800 italic uppercase tracking-tighter">{formData.name || 'Untitled Event'}</h3>
                   </div>
                   <div className="flex flex-wrap gap-4">
                      <div className="px-4 py-2 bg-slate-100 rounded-xl text-[10px] font-black uppercase tracking-widest">{formData.type}</div>
                      <div className="px-4 py-2 bg-slate-100 rounded-xl text-[10px] font-black uppercase tracking-widest">{formData.date}</div>
                      <div className="px-4 py-2 bg-slate-100 rounded-xl text-[10px] font-black uppercase tracking-widest">{formData.startTime} - {formData.endTime}</div>
                      <div className="px-4 py-2 bg-indigo-50 text-indigo-600 rounded-xl text-[10px] font-black uppercase tracking-widest">{formData.location}</div>
                   </div>
                </div>
                <div className="bg-emerald-50 p-8 rounded-[40px] border border-emerald-100">
                   <h4 className="text-sm font-black text-emerald-900 uppercase italic mb-3 flex items-center gap-2"><Zap size={16} fill="currentColor" /> Synthesis Preview</h4>
                   <ul className="space-y-2">
                      <li className="text-[10px] font-bold text-emerald-700 uppercase tracking-wide">• Personnel assigned to {formData.location}</li>
                      <li className="text-[10px] font-bold text-emerald-700 uppercase tracking-wide">• {formData.performers.filter(p => p.tableAssignment).length} VIP Table Reservations Placed</li>
                      <li className="text-[10px] font-bold text-emerald-700 uppercase tracking-wide">• 4 Dept Briefing Sheets Created</li>
                   </ul>
                </div>
             </div>
          </div>
        )}

        <div className="mt-auto pt-12 flex justify-between">
           <button 
            onClick={prevStep} 
            disabled={step === 1}
            className="px-10 py-5 bg-slate-100 text-slate-400 rounded-3xl text-[10px] font-black uppercase tracking-widest disabled:opacity-0 transition-all flex items-center gap-2"
           >
             <ChevronLeft size={16} /> Previous
           </button>
           
           {step < 5 ? (
             <button 
              onClick={nextStep}
              className="px-12 py-5 bg-brand-primary text-white rounded-3xl text-[10px] font-black uppercase tracking-widest shadow-xl shadow-brand-primary/20 hover:scale-[1.02] transition-all flex items-center gap-2"
             >
               Next Phase <ChevronRight size={16} />
             </button>
           ) : (
             <button 
              onClick={handleSave}
              className="px-12 py-5 bg-emerald-500 text-white rounded-3xl text-[10px] font-black uppercase tracking-widest shadow-xl shadow-emerald-500/20 hover:scale-[1.02] transition-all flex items-center gap-2"
             >
               {initialData ? 'Update Record' : 'Fire Event Architect'} <Save size={16} />
             </button>
           )}
        </div>
      </div>
    </div>
  );
};

export default NewEventForm;
